# Biblioteca Pandas
<hr />

* Biblioteca open source, escrita sobre a NumPy, extremamente eficiente para limpeza e manipulação de grandes quantidades de dados. Trabalha os dados de forma muito semelhante ao MS Excel (linhas e colunas).

* Oferece estruturas e funções para facilitar a análise de dados em Python. Originalmente suas funções eram concentradas para análise de séries temporais, porém foi evoluindo e hoje possui suporte para diversos tipos de dados.

* Outra grande vantagem é que boa parte do código foi implementada em linguagem C para melhorar a performance. Assim como a biblioteca NumPy buscou-se a facilidade da linguagem Python com a performance similar à da linguagem C.

> http://pandas.pydata.org/

* Sua instalação é bastante simples, feita através do PIP ou Conda:

    ```javascript
        pip install pandas      ou      conda install pandas
    ```

**Neste módulo serão abordados os principais objetos do Pandas:**
* Series
* DataFrames
* Agrupamentos (GroupBy)
* Entrada e Saída de dados
* Índices Multiníveis
* Dados Faltantes
* Concatenação e mesclagem

In [76]:
import numpy as np
import pandas as pd

## Series

### Uma Series é como um array unidimensional, uma lista de valores que sempre tem um índice relacionado, que rotula cada elemento da lista formando uma estrutura semelhante a de um dicionário do Python.

In [77]:
lista = [10, 20, 30]
array = np.array([10, 20, 30])
dic = {'A':10, 'B':20, 'C':30}

In [78]:
my_list = pd.Series(lista)
my_list

0    10
1    20
2    30
dtype: int64

In [79]:
coord = pd.Series(lista, ['X', 'Y', 'Z'])
coord

X    10
Y    20
Z    30
dtype: int64

In [80]:
pd.Series(['X', 'Y', 'Z'], lista)

10    X
20    Y
30    Z
dtype: object

In [81]:
pd.Series(array)

0    10
1    20
2    30
dtype: int64

In [82]:
s = pd.Series(dic)
s

A    10
B    20
C    30
dtype: int64

In [83]:
type(s)

pandas.core.series.Series

### Elementos podem ser acessados através de seu índice:

In [84]:
coord['Y']

20

In [85]:
my_list[0]

10

_**NOTE** que tanto índices quanto valores podem ser de qualquer tipo do Python ou de qualquer biblioteca referenciada_.

### Fornece informações estatísticas básicas sobre a série (no caso de séries numéricas):

In [86]:
array = np.random.randint(1, 100, 10)
series = pd.Series(array)
series

0    74
1    55
2    93
3    67
4    17
5     6
6    52
7    91
8    35
9    68
dtype: int64

In [87]:
series.mean()

55.8

In [88]:
series.std()

29.176855363265055

In [89]:
series.min()

6

In [90]:
series.max()

93

In [91]:
series.value_counts()

74    1
55    1
93    1
67    1
17    1
6     1
52    1
91    1
35    1
68    1
dtype: int64

In [92]:
series.describe()

count    10.000000
mean     55.800000
std      29.176855
min       6.000000
25%      39.250000
50%      61.000000
75%      72.500000
max      93.000000
dtype: float64

### Operações com escalares:

In [93]:
pd.Series([10, 20, 30, 40, 50]) / 10

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64

In [94]:
pd.Series([10, 20, 30, 40, 50]) * 10

0    100
1    200
2    300
3    400
4    500
dtype: int64

### Operações baseadas em indices:

In [95]:
female_by_uf = pd.Series([1142487, 1185868, 248416, 5509991], ['AL', 'AM', 'AP', 'BA'])

In [96]:
male_by_uf = pd.Series([1004033, 1134335, 239029, 5053946], ['AL', 'AM', 'AP', 'BA'])

In [97]:
total_by_uf = female_by_uf + male_by_uf

In [98]:
total_by_uf

AL     2146520
AM     2320203
AP      487445
BA    10563937
dtype: int64

In [99]:
female_by_uf = pd.Series([71850, 1142487, 1185868, 248416, 5509991], ['AC', 'AL', 'AM', 'AP', 'BA'])

In [100]:
male_by_uf = pd.Series([1004033, 1134335, 239029, 5053946, 2991782, 1301956], ['AL', 'AM', 'AP', 'BA', 'CE', 'ES'])

In [101]:
total_by_uf = female_by_uf + male_by_uf

In [102]:
total_by_uf

AC           NaN
AL     2146520.0
AM     2320203.0
AP      487445.0
BA    10563937.0
CE           NaN
ES           NaN
dtype: float64

## DataFrame

### DataFrame é o principal objeto da biblioteca Pandas. É composto basicamente por conjuntos de Series organizados de forma bidimensional e indexados.

### Pode ser criado de várias formas diferentes:

In [103]:
df = pd.DataFrame([[10, 20, 30], [40, 50 , 60], [70, 80, 90]])
df

    0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

In [104]:
np.random.seed(100)

In [105]:
df = pd.DataFrame(np.random.randn(5, 4))
df

          0         1         2         3
0 -1.749765  0.342680  1.153036 -0.252436
1  0.981321  0.514219  0.221180 -1.070043
2 -0.189496  0.255001 -0.458027  0.435163
3 -0.583595  0.816847  0.672721 -0.104411
4 -0.531280  1.029733 -0.438136 -1.118318

In [106]:
df = pd.DataFrame(np.random.randn(5, 4), index=['A', 'B', 'C', 'D', 'E'])
df

          0         1         2         3
A  1.618982  1.541605 -0.251879 -0.842436
B  0.184519  0.937082  0.731000  1.361556
C -0.326238  0.055676  0.222400 -1.443217
D -0.756352  0.816454  0.750445 -0.455947
E  1.189622 -1.690617 -1.356399 -1.232435

In [107]:
df = pd.DataFrame(np.random.randn(5, 4), columns=['A', 'B', 'C', 'D'])
df

          A         B         C         D
0 -0.544439 -0.668172  0.007315 -0.612939
1  1.299748 -1.733096 -0.983310  0.357508
2 -1.613579  1.470714 -1.188018 -0.549746
3 -0.940046 -0.827932  0.108863  0.507810
4 -0.862227  1.249470 -0.079611 -0.889731

In [108]:
df = pd.DataFrame(np.random.randn(5, 4), 
                  index=['A', 'B', 'C', 'D', 'E'], 
                  columns=['W', 'X', 'Y', 'Z'])
df

          W         X         Y         Z
A -0.881798  0.018639  0.237845  0.013549
B -1.635529 -1.044210  0.613039  0.736205
C  1.026921 -1.432191 -1.841188  0.366093
D -0.331777 -0.689218  2.034608 -0.550714
E  0.750453 -1.306992  0.580573 -1.104523

### A indexação de um DataFrame é muito semelhante à de utilizadas em dicionários:
**As colunas de um DataFrame são Series**

In [109]:
df['W']

A   -0.881798
B   -1.635529
C    1.026921
D   -0.331777
E    0.750453
Name: W, dtype: float64

In [110]:
df[['W', 'Y']]

          W         Y
A -0.881798  0.237845
B -1.635529  0.613039
C  1.026921 -1.841188
D -0.331777  2.034608
E  0.750453  0.580573

### É possível criar novas colunas apenas atribuindo uma Series a ela:

In [111]:
df['X_Y'] = df['X'] + df['Y']
df

          W         X         Y         Z       X_Y
A -0.881798  0.018639  0.237845  0.013549  0.256484
B -1.635529 -1.044210  0.613039  0.736205 -0.431171
C  1.026921 -1.432191 -1.841188  0.366093 -3.273379
D -0.331777 -0.689218  2.034608 -0.550714  1.345390
E  0.750453 -1.306992  0.580573 -1.104523 -0.726419

In [112]:
df['Another'] = [23, 456, 89, -34, 66]
df

          W         X         Y         Z       X_Y  Another
A -0.881798  0.018639  0.237845  0.013549  0.256484       23
B -1.635529 -1.044210  0.613039  0.736205 -0.431171      456
C  1.026921 -1.432191 -1.841188  0.366093 -3.273379       89
D -0.331777 -0.689218  2.034608 -0.550714  1.345390      -34
E  0.750453 -1.306992  0.580573 -1.104523 -0.726419       66

In [113]:
df['W']

A   -0.881798
B   -1.635529
C    1.026921
D   -0.331777
E    0.750453
Name: W, dtype: float64

In [114]:
df.drop('X_Y', axis=1)

          W         X         Y         Z  Another
A -0.881798  0.018639  0.237845  0.013549       23
B -1.635529 -1.044210  0.613039  0.736205      456
C  1.026921 -1.432191 -1.841188  0.366093       89
D -0.331777 -0.689218  2.034608 -0.550714      -34
E  0.750453 -1.306992  0.580573 -1.104523       66

In [115]:
df

          W         X         Y         Z       X_Y  Another
A -0.881798  0.018639  0.237845  0.013549  0.256484       23
B -1.635529 -1.044210  0.613039  0.736205 -0.431171      456
C  1.026921 -1.432191 -1.841188  0.366093 -3.273379       89
D -0.331777 -0.689218  2.034608 -0.550714  1.345390      -34
E  0.750453 -1.306992  0.580573 -1.104523 -0.726419       66

### Porém esta operação não afeta diretamente o DataFrame, para que isso ocorra é necessário utilizar o parâmetro *inplace*.

In [116]:
df.drop('X_Y', axis=1, inplace=True)
df

          W         X         Y         Z  Another
A -0.881798  0.018639  0.237845  0.013549       23
B -1.635529 -1.044210  0.613039  0.736205      456
C  1.026921 -1.432191 -1.841188  0.366093       89
D -0.331777 -0.689218  2.034608 -0.550714      -34
E  0.750453 -1.306992  0.580573 -1.104523       66

In [117]:
df = df.drop('Another', axis=1)
df

          W         X         Y         Z
A -0.881798  0.018639  0.237845  0.013549
B -1.635529 -1.044210  0.613039  0.736205
C  1.026921 -1.432191 -1.841188  0.366093
D -0.331777 -0.689218  2.034608 -0.550714
E  0.750453 -1.306992  0.580573 -1.104523

### Elementos podem ser localizados usando o método *loc* seguindo a notação de linha X coluna:

In [118]:
df

          W         X         Y         Z
A -0.881798  0.018639  0.237845  0.013549
B -1.635529 -1.044210  0.613039  0.736205
C  1.026921 -1.432191 -1.841188  0.366093
D -0.331777 -0.689218  2.034608 -0.550714
E  0.750453 -1.306992  0.580573 -1.104523

In [119]:
df.loc['A', 'W']

-0.8817983894830175

In [120]:
df.loc['C', 'Y']

-1.841188300186717

### Quando a coluna é omitida, o retorno serão todos os elementos da linha selecionada em formato Series:

In [121]:
df.loc['A']

W   -0.881798
X    0.018639
Y    0.237845
Z    0.013549
Name: A, dtype: float64

In [122]:
df.loc['C']

W    1.026921
X   -1.432191
Y   -1.841188
Z    0.366093
Name: C, dtype: float64

### A notação linha X coluna também pode ser utilizada:

In [123]:
df.loc[['A', 'C'], ['Y', 'Z']]

          Y         Z
A  0.237845  0.013549
C -1.841188  0.366093

### É possivel localizar elementos através de índices numéricos assim como na NumPy através do método *iloc*:

In [124]:
df.iloc[1:4]

          W         X         Y         Z
B -1.635529 -1.044210  0.613039  0.736205
C  1.026921 -1.432191 -1.841188  0.366093
D -0.331777 -0.689218  2.034608 -0.550714

In [125]:
df.iloc[:2, 2:]

          Y         Z
A  0.237845  0.013549
B  0.613039  0.736205

### De uma forma muito semelhante à seleção condicional do NumPy, com os Dataframes e Series do Pandas é possível localizar elementos baseado em condições além da localização por linhas, colunas ou índices:

In [126]:
df > 0

       W      X      Y      Z
A  False   True   True   True
B  False  False   True   True
C   True  False  False   True
D  False  False   True  False
E   True  False   True  False

In [127]:
df[df > 0]

          W         X         Y         Z
A       NaN  0.018639  0.237845  0.013549
B       NaN       NaN  0.613039  0.736205
C  1.026921       NaN       NaN  0.366093
D       NaN       NaN  2.034608       NaN
E  0.750453       NaN  0.580573       NaN

#### Note que os indices dos elementos que não obedecem ao critério estabelecido, retornam com NaN (Não disponível)

### A partir do DataFrame resultante, é possível fazer operações de *slicing*:

In [128]:
df[df['W'] > 0]

          W         X         Y         Z
C  1.026921 -1.432191 -1.841188  0.366093
E  0.750453 -1.306992  0.580573 -1.104523

In [129]:
df[df['W'] > 0][['X', 'Y']]

          X         Y
C -1.432191 -1.841188
E -1.306992  0.580573

In [130]:

df[df['W'] > 0][['X', 'Y']][1:]

          X         Y
E -1.306992  0.580573

### É possível combinar condições em uma seleção condicional utilizando os operadores & e |

In [131]:
mask1 = df['W'] > 0
df[mask1]

          W         X         Y         Z
C  1.026921 -1.432191 -1.841188  0.366093
E  0.750453 -1.306992  0.580573 -1.104523

In [132]:
df[((df['X'] < 0) & (df['Y'] > 0) | (df['Z'] < 0))]

          W         X         Y         Z
B -1.635529 -1.044210  0.613039  0.736205
D -0.331777 -0.689218  2.034608 -0.550714
E  0.750453 -1.306992  0.580573 -1.104523

### É possível reiniciar as condições do índice de um DataFrame através do método *reset_index*:

In [133]:
df.reset_index()

  index         W         X         Y         Z
0     A -0.881798  0.018639  0.237845  0.013549
1     B -1.635529 -1.044210  0.613039  0.736205
2     C  1.026921 -1.432191 -1.841188  0.366093
3     D -0.331777 -0.689218  2.034608 -0.550714
4     E  0.750453 -1.306992  0.580573 -1.104523

### Ou substituir o índice por valores de uma coluna do DataFrame qualquer:

In [134]:
df

          W         X         Y         Z
A -0.881798  0.018639  0.237845  0.013549
B -1.635529 -1.044210  0.613039  0.736205
C  1.026921 -1.432191 -1.841188  0.366093
D -0.331777 -0.689218  2.034608 -0.550714
E  0.750453 -1.306992  0.580573 -1.104523

In [135]:
df['Estados'] = ['SP', 'RJ', 'MG', 'ES', 'SC']

In [136]:
df.set_index('Estados')
df

          W         X         Y         Z Estados
A -0.881798  0.018639  0.237845  0.013549      SP
B -1.635529 -1.044210  0.613039  0.736205      RJ
C  1.026921 -1.432191 -1.841188  0.366093      MG
D -0.331777 -0.689218  2.034608 -0.550714      ES
E  0.750453 -1.306992  0.580573 -1.104523      SC

### Operações de agrupamento podem ser efetuadas através do método *groupby*:

In [137]:
data = {'Team' : ['Alfa', 'Beta', 'Alfa', 'Beta', 'Beta', 'Alfa'], 
        'Seller' : ['Bob', 'Sam', 'Charlie', 'Smith', 'Sam', 'Bob'],
        'Sale' : [120, 250, 180, 100, 95, 278]}

df = pd.DataFrame(data)
df

   Team   Seller  Sale
0  Alfa      Bob   120
1  Beta      Sam   250
2  Alfa  Charlie   180
3  Beta    Smith   100
4  Beta      Sam    95
5  Alfa      Bob   278

In [138]:
by_team = df.groupby(by='Team')
by_team

In [139]:
df.index

RangeIndex(start=0, stop=6, step=1)

### Várias informações podem ser extraídas a partir de um *DataFrameGroupBy*:

In [140]:
by_team.sum()

<ipython-input-140-487821834340>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  by_team.sum()

      Sale
Team
Alfa   578
Beta   445

In [141]:
by_team.max()

       Seller  Sale
Team
Alfa  Charlie   278
Beta    Smith   250

In [142]:
by_team.min()

     Seller  Sale
Team
Alfa    Bob   120
Beta    Sam    95

In [143]:
by_team.mean()

<ipython-input-143-7aaa92c6e8c6>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  by_team.mean()

            Sale
Team
Alfa  192.666667
Beta  148.333333

In [144]:
by_team.std()

<ipython-input-144-48e303a3a963>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.std is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  by_team.std()

           Sale
Team
Alfa  79.757967
Beta  88.081402

### Algumas informações estatísticas podem ser obtidas através do método *describe*:

In [145]:
by_seller = df.groupby(by='Seller')
by_seller

In [146]:
by_seller.describe()

         Sale
        count   mean         std    min     25%    50%     75%    max
Seller
Bob       2.0  199.0  111.722871  120.0  159.50  199.0  238.50  278.0
Charlie   1.0  180.0         NaN  180.0  180.00  180.0  180.00  180.0
Sam       2.0  172.5  109.601551   95.0  133.75  172.5  211.25  250.0
Smith     1.0  100.0         NaN  100.0  100.00  100.0  100.00  100.0

### As operações de agrupamento, retornam DataFrames que podem ser fatiados:

In [147]:
s = by_seller.sum()
s

<ipython-input-147-26d76b2e7ce6>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  s = by_seller.sum()

         Sale
Seller
Bob       398
Charlie   180
Sam       345
Smith     100

In [148]:
s.loc['Bob']

Sale    398
Name: Bob, dtype: int64

In [149]:
s[s['Sale'] > 200]

        Sale
Seller
Bob      398
Sam      345

### Pandas fornece uma série de métodos para entrada e saída de dados. Basicamente em uma operação é possível ler um conjunto de dados de uma determinada fonte de forma que sejam já disponibilizadas em um DataFrame.

### Para isso é necessário conhecer o tipo e as características da fonte de dados, por exemplo, um arquivo CSV, seu separador e encoding. Os métodos *read_\** e *to_\** fornecem o suporte necessário para tal tarefa:

In [150]:
df = pd.read_csv('/content/heroes.csv')
df.head()

,id,name,Gender,Eye color,Race,Hair color,Height,Publisher,Skin color,Alignment,Weight
0,0,A-Bomb,Male,yellow,Human,No Hair,203.0,Marvel Comics,-,good,441.0
1,1,Abe Sapien,Male,blue,Icthyo Sapien,No Hair,191.0,Dark Horse Comics,blue,good,65.0
2,2,Abin Sur,Male,blue,Ungaran,No Hair,185.0,DC Comics,red,good,90.0
3,3,Abomination,Male,green,Human / Radiation,No Hair,203.0,Marvel Comics,-,bad,441.0
4,4,Abraxas,Male,blue,Cosmic Entity,Black,-99.0,Marvel Comics,-,bad,-99.0

In [151]:
data = {'Team' : ['Alfa', 'Beta', 'Alfa', 'Beta', 'Beta', 'Alfa'], 
        'Seller' : ['Bob', 'Sam', 'Charlie', 'Smith', 'Sam', 'Bob'],
        'Sale' : [120, 250, 180, 100, 95, 278]}

df = pd.DataFrame(data)
df.to_csv('/tmp/sales.csv')
df.to_json('/tmp/sales.json')

## Índices Multiníveis

In [152]:
groups = [('Grupo 1', 'Sub_1'), 
          ('Grupo 1', 'Sub_2'), 
          ('Grupo 1', 'Sub_3'),
          ('Grupo 2', 'Sub_1'), 
          ('Grupo 2', 'Sub_2'), 
          ('Grupo 2', 'Sub_3')]
groups

[('Grupo 1', 'Sub_1'),
 ('Grupo 1', 'Sub_2'),
 ('Grupo 1', 'Sub_3'),
 ('Grupo 2', 'Sub_1'),
 ('Grupo 2', 'Sub_2'),
 ('Grupo 2', 'Sub_3')]

In [153]:
i = pd.MultiIndex.from_tuples(groups)
i

MultiIndex([('Grupo 1', 'Sub_1'),
            ('Grupo 1', 'Sub_2'),
            ('Grupo 1', 'Sub_3'),
            ('Grupo 2', 'Sub_1'),
            ('Grupo 2', 'Sub_2'),
            ('Grupo 2', 'Sub_3')],
           )

In [154]:
df = pd.DataFrame(np.random.rand(6, 2), index=i, columns=['C1', 'C2'])
df

                     C1        C2
Grupo 1 Sub_1  0.778289  0.779598
        Sub_2  0.610328  0.309000
        Sub_3  0.697735  0.859618
Grupo 2 Sub_1  0.625324  0.982408
        Sub_2  0.976500  0.166694
        Sub_3  0.023178  0.160745

In [155]:
df.index.names = ['Grupo', 'SubGrupo']
df

                        C1        C2
Grupo   SubGrupo
Grupo 1 Sub_1     0.778289  0.779598
        Sub_2     0.610328  0.309000
        Sub_3     0.697735  0.859618
Grupo 2 Sub_1     0.625324  0.982408
        Sub_2     0.976500  0.166694
        Sub_3     0.023178  0.160745

In [156]:
g1 = df.loc['Grupo 1']
g1

                C1        C2
SubGrupo
Sub_1     0.778289  0.779598
Sub_2     0.610328  0.309000
Sub_3     0.697735  0.859618

In [157]:
g1['C1']

SubGrupo
Sub_1    0.778289
Sub_2    0.610328
Sub_3    0.697735
Name: C1, dtype: float64

In [158]:
g1.loc['Sub_1']

C1    0.778289
C2    0.779598
Name: Sub_1, dtype: float64

In [159]:
df.xs(key='Sub_1', level=1)

               C1        C2
Grupo
Grupo 1  0.778289  0.779598
Grupo 2  0.625324  0.982408

In [160]:
df.xs(key='Grupo 1', level=0)

                C1        C2
SubGrupo
Sub_1     0.778289  0.779598
Sub_2     0.610328  0.309000
Sub_3     0.697735  0.859618

In [161]:
data = {'Team' : ['Alfa', 'Beta', 'Alfa', 'Beta', 'Beta', 'Alfa'], 
        'Seller' : ['Bob', 'Sam', 'Charlie', 'Smith', 'Sam', 'Bob'],
        'Sale' : [120, 250, 180, 100, 95, 278]}

df = pd.DataFrame(data)
df

   Team   Seller  Sale
0  Alfa      Bob   120
1  Beta      Sam   250
2  Alfa  Charlie   180
3  Beta    Smith   100
4  Beta      Sam    95
5  Alfa      Bob   278

In [162]:
df = df.groupby(by=['Team', 'Seller']).sum()
df

              Sale
Team Seller
Alfa Bob       398
     Charlie   180
Beta Sam       345
     Smith     100

In [163]:
df.index

MultiIndex([('Alfa',     'Bob'),
            ('Alfa', 'Charlie'),
            ('Beta',     'Sam'),
            ('Beta',   'Smith')],
           names=['Team', 'Seller'])

In [164]:
df.xs(key='Bob', level=1)

      Sale
Team
Alfa   398

In [165]:
df.xs(key='Beta', level=0)

        Sale
Seller
Sam      345
Smith    100

## Dados Faltantes

Eventualmente poderá ocorrer uma situação onde o conjunto de informações fornecido tenha alguns _gaps_, algumas informações que não foram forneceidas em meio a muitas outras fornecidas, e esses "buracos" podem atrapalhar a análise do _DataSet_ pois as operações estatísticas básicas acabam não funcionando de forma adequada.

O Pandas oferece algumas funcionalidades para contornar esses problemas e a utilização desses métodos irá depender do comportamento esperado do tratamento desses dados:

### Método: dropna()
Este método excluirá (_drop_), dependendo dos parâmetros de entrada, linhas ou colunas com dados faltantes.

In [166]:
df = pd.DataFrame({'A':[1, 2, 3], 'B':[np.nan, 4, 5], 'C':[np.nan, 7, np.nan]})
df

   A    B    C
0  1  NaN  NaN
1  2  4.0  7.0
2  3  5.0  NaN

In [167]:
df.dropna()

   A    B    C
1  2  4.0  7.0

In [168]:
df.dropna(axis=1)

   A
0  1
1  2
2  3

In [169]:
df.dropna(axis=1, thresh=2)

   A    B
0  1  NaN
1  2  4.0
2  3  5.0

### Método: fillna()
O método _fillna()_ irá preencher os dados faltantes com critérios passados nos argumentos.

In [170]:
df.fillna(0)

   A    B    C
0  1  0.0  0.0
1  2  4.0  7.0
2  3  5.0  0.0

In [171]:
df.fillna(df.mean())

   A    B    C
0  1  4.5  7.0
1  2  4.0  7.0
2  3  5.0  7.0

In [172]:
df.fillna(df.min())

   A    B    C
0  1  4.0  7.0
1  2  4.0  7.0
2  3  5.0  7.0

In [173]:
df.fillna(df.max())

   A    B    C
0  1  5.0  7.0
1  2  4.0  7.0
2  3  5.0  7.0

In [174]:
df = pd.DataFrame([[np.nan, 2, np.nan, 0],
                   [3, 4, np.nan, 1],
                   [np.nan, np.nan, np.nan, 5],
                   [np.nan, 3, np.nan, 4]],
                  columns=list('ABCD'))
df

     A    B   C  D
0  NaN  2.0 NaN  0
1  3.0  4.0 NaN  1
2  NaN  NaN NaN  5
3  NaN  3.0 NaN  4

In [175]:
df.fillna(method='ffill')

     A    B   C  D
0  NaN  2.0 NaN  0
1  3.0  4.0 NaN  1
2  3.0  4.0 NaN  5
3  3.0  3.0 NaN  4

In [176]:
df.fillna(value={'A': 0, 'B': 99, 'C': -1, 'D': 'A'})

     A     B    C  D
0  0.0   2.0 -1.0  0
1  3.0   4.0 -1.0  1
2  0.0  99.0 -1.0  5
3  0.0   3.0 -1.0  4

In [177]:
df.fillna(value={'A': 0, 'B': 99, 'C': -1, 'D': 'A'}, limit=1)

     A     B    C  D
0  0.0   2.0 -1.0  0
1  3.0   4.0  NaN  1
2  NaN  99.0  NaN  5
3  NaN   3.0  NaN  4

### Método: replace()
O método replace substitui um valor por outro passados como argumentos, podendo aceitar escalares, cadeias de caracteres, listas e expressões regulares.

In [178]:
s = pd.Series([0, 1, 2, 3, 4])
s

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [179]:
s.replace(0, 5)

0    5
1    1
2    2
3    3
4    4
dtype: int64

In [180]:
df = pd.DataFrame({'A': [0, 1, 2, 3, 4],
                   'B': [5, 6, 7, 8, 9],
                   'C': ['a', 'b', 'c', 'd', 'e']})
df

   A  B  C
0  0  5  a
1  1  6  b
2  2  7  c
3  3  8  d
4  4  9  e

In [181]:
df.replace(0, 5)

   A  B  C
0  5  5  a
1  1  6  b
2  2  7  c
3  3  8  d
4  4  9  e

In [182]:
df.replace([0, 1, 2, 3, 7], -1)

   A  B  C
0 -1  5  a
1 -1  6  b
2 -1 -1  c
3 -1  8  d
4  4  9  e

In [183]:
df.replace([0, 1, 2, 3], [4, 3, 2, 1])

   A  B  C
0  4  5  a
1  3  6  b
2  2  7  c
3  1  8  d
4  4  9  e

In [184]:
x = df.replace([0, 1, 2, 3], np.nan)
x

     A  B  C
0  NaN  5  a
1  NaN  6  b
2  NaN  7  c
3  NaN  8  d
4  4.0  9  e

In [185]:
x.replace(np.nan, -1)

     A  B  C
0 -1.0  5  a
1 -1.0  6  b
2 -1.0  7  c
3 -1.0  8  d
4  4.0  9  e

In [186]:
df.replace([1, 2], method='bfill')

   A  B  C
0  0  5  a
1  3  6  b
2  3  7  c
3  3  8  d
4  4  9  e

In [187]:
df.replace({0: 10, 1: 'A', 'c': 'Python'})

    A  B       C
0  10  5       a
1   A  6       b
2   2  7  Python
3   3  8       d
4   4  9       e

In [188]:
df.replace({'A': 0, 'B': 8}, 100)

     A    B  C
0  100    5  a
1    1    6  b
2    2    7  c
3    3  100  d
4    4    9  e

## Concatenação, junção e mesclagem
Existem 3 formas diferentes de combinar DataFramas do Pandas: _Merging_, _Joining_ e _Concatenating_. Em todas elas o objetivo é o mesmo, trazer informações de DataFrames dispersos para um único DataFrame, com o objetivo de facilitar a análise dos dados.

https://pandas.pydata.org/pandas-docs/stable/merging.html

## Método: concat()

In [189]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']})

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']}) 

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                    'B': ['B8', 'B9', 'B10', 'B11'],
                    'C': ['C8', 'C9', 'C10', 'C11'],
                    'D': ['D8', 'D9', 'D10', 'D11']})

In [190]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [191]:
df2

    A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [192]:
df3

     A    B    C    D
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

In [193]:
pd.concat([df1, df2, df3])

     A    B    C    D
0   A0   B0   C0   D0
1   A1   B1   C1   D1
2   A2   B2   C2   D2
3   A3   B3   C3   D3
0   A4   B4   C4   D4
1   A5   B5   C5   D5
2   A6   B6   C6   D6
3   A7   B7   C7   D7
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

In [194]:
pd.concat([df1, df2, df3], ignore_index=True)

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [195]:
pd.concat([df1, df2, df3], axis=1)

    A   B   C   D   A   B   C   D    A    B    C    D
0  A0  B0  C0  D0  A4  B4  C4  D4   A8   B8   C8   D8
1  A1  B1  C1  D1  A5  B5  C5  D5   A9   B9   C9   D9
2  A2  B2  C2  D2  A6  B6  C6  D6  A10  B10  C10  D10
3  A3  B3  C3  D3  A7  B7  C7  D7  A11  B11  C11  D11

In [196]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11'], 
                        'F': ['F1', 'F2', 'F3', 'F4']})

In [197]:
df3

     A    B    C    D   F
0   A8   B8   C8   D8  F1
1   A9   B9   C9   D9  F2
2  A10  B10  C10  D10  F3
3  A11  B11  C11  D11  F4

In [198]:
pd.concat([df1, df2, df3], sort=False)

     A    B    C    D    F
0   A0   B0   C0   D0  NaN
1   A1   B1   C1   D1  NaN
2   A2   B2   C2   D2  NaN
3   A3   B3   C3   D3  NaN
0   A4   B4   C4   D4  NaN
1   A5   B5   C5   D5  NaN
2   A6   B6   C6   D6  NaN
3   A7   B7   C7   D7  NaN
0   A8   B8   C8   D8   F1
1   A9   B9   C9   D9   F2
2  A10  B10  C10  D10   F3
3  A11  B11  C11  D11   F4

In [199]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                    index=[0, 1, 2, 3])

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']},
                     index=[4, 5, 6, 7])

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                    'B': ['B8', 'B9', 'B10', 'B11'],
                    'C': ['C8', 'C9', 'C10', 'C11'],
                    'D': ['D8', 'D9', 'D10', 'D11']},
                    index=[8, 9, 10, 11])

In [200]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [201]:
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [202]:
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [203]:
pd.concat([df1, df2, df3], axis=1)

      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

### Método: merge()

In [204]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                       'A': ['A0', 'A1', 'A2', 'A3'],
                       'B': ['B0', 'B1', 'B2', 'B3']})

right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']})

In [205]:
left

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [206]:
right

  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [207]:
pd.merge(left, right, on='key')

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [208]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})

right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                      'key2': ['K0', 'K0', 'K0', 'K0'],
                         'C': ['C0', 'C1', 'C2', 'C3'],
                         'D': ['D0', 'D1', 'D2', 'D3']})

In [209]:
left

  key1 key2   A   B
0   K0   K0  A0  B0
1   K0   K1  A1  B1
2   K1   K0  A2  B2
3   K2   K1  A3  B3

In [210]:
right

  key1 key2   C   D
0   K0   K0  C0  D0
1   K1   K0  C1  D1
2   K1   K0  C2  D2
3   K2   K0  C3  D3

In [211]:
pd.merge(left, right, on=['key1', 'key2'])

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [212]:
pd.merge(left, right, how='left', on=['key1', 'key2'])

  key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

In [213]:
pd.merge(left, right, how='right', on=['key1', 'key2'])

  key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [214]:
pd.merge(left, right, how='outer', on=['key1', 'key2'])

  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K1   A3   B3  NaN  NaN
5   K2   K0  NaN  NaN   C3   D3

### Método: join()

In [215]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                     index=['K0', 'K1', 'K2'])

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                      'D': ['D0', 'D2', 'D3']},
                     index=['K0', 'K2', 'K3'])

In [216]:
left

     A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [217]:
right

     C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3

In [218]:
left.join(right)

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [219]:
left.join(right, how='outer')

      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

In [220]:
left.join(right, how='left')

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [221]:
left.join(right, how='right')

      A    B   C   D
K0   A0   B0  C0  D0
K2   A2   B2  C2  D2
K3  NaN  NaN  C3  D3