# Explorando o Pandas com um Dataset

Fonte: https://www.kaggle.com/datasets/aungpyaeap/supermarket-sales?resource=download

<hr />

### 1 - Explorando o dataset:

In [ ]:
# Importando o Numpy e Pandas:
import numpy as np
import pandas as pd

In [ ]:
# Carregando arquivo .csv:
df = pd.read_csv('./supermarket.csv')

In [ ]:
# Mostrado os 05 primeiros registros do Data Frame:
df.head(5)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3

In [ ]:
# Mostrando os 05 últimos registros do Data Frame:
df.tail(5)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,6.6

In [ ]:
# Visualizando os detalhes e dados estatísticos do Data Frame:
df.describe()

,Unit price,Quantity,Tax 5%,Total,cogs,gross margin percentage,gross income,Rating
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.00000
mean,55.672130,5.510000,15.379369,322.966749,307.58738,4.761905,15.379369,6.97270
std,26.494628,2.923431,11.708825,245.885335,234.17651,0.000000,11.708825,1.71858
min,10.080000,1.000000,0.508500,10.678500,10.17000,4.761905,0.508500,4.00000
25%,32.875000,3.000000,5.924875,124.422375,118.49750,4.761905,5.924875,5.50000
50%,55.230000,5.000000,12.088000,253.848000,241.76000,4.761905,12.088000,7.00000
75%,77.935000,8.000000,22.445250,471.350250,448.90500,4.761905,22.445250,8.50000
max,99.960000,10.000000,49.650000,1042.650000,993.00000,4.761905,49.650000,10.00000

### 2 - Exportando para outros formatos:

In [ ]:
# Exportando o Data Frame para outros formatos:
df.to_excel('excel_supermarket.xlsx', sheet_name='Sheet1')
df.to_json('supermarket.json')

### 3 - Selecionando os dados e realizando operações:

In [ ]:
# Recuperando os dados de uma coluna apenas:
df['City']

0         Yangon
1      Naypyitaw
2         Yangon
3         Yangon
4         Yangon
         ...
995    Naypyitaw
996     Mandalay
997       Yangon
998       Yangon
999       Yangon
Name: City, Length: 1000, dtype: object

In [ ]:
# Recuperando dados de um grupo de colunas:
df[['City', 'Total']]

          City      Total
0       Yangon   548.9715
1    Naypyitaw    80.2200
2       Yangon   340.5255
3       Yangon   489.0480
4       Yangon   634.3785
..         ...        ...
995  Naypyitaw    42.3675
996   Mandalay  1022.4900
997     Yangon    33.4320
998     Yangon    69.1110
999     Yangon   649.2990

[1000 rows x 2 columns]

In [ ]:
# Aplicando o describe() apenas para uma coluna:
df['City'].describe()

count       1000
unique         3
top       Yangon
freq         340
Name: City, dtype: object

In [ ]:
# Visualizado um resumo geral do Data Frame:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   object
 1   Branch                   1000 non-null   object
 2   City                     1000 non-null   object
 3   Customer type            1000 non-null   object
 4   Gender                   1000 non-null   object
 5   Product line             1000 non-null   object
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Total                    1000 non-null   float64
 10  Date                     1000 non-null   object
 11  Time                     1000 non-null   object
 12  Payment                  1000 non-null   object
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: float64(7), int64(1), object(9)
memory usage: 132.9+ KB

In [ ]:
# Visualizando a quantidade de linhas x colunas do Data Frame:
df.shape

(1000, 17)

In [ ]:
# Ordenando os dados do Data Frame de acordo com uma das colunas:
df.sort_values('Total')

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
822,784-21-9238,C,Naypyitaw,Member,Male,Sports and travel,10.17,1,0.5085,10.6785,2/7/2019,14:15,Cash,10.17,4.761905,0.5085,5.9
629,308-39-1707,A,Yangon,Normal,Female,Fashion accessories,12.09,1,0.6045,12.6945,1/26/2019,18:19,Credit card,12.09,4.761905,0.6045,8.2
223,279-62-1445,C,Naypyitaw,Member,Female,Fashion accessories,12.54,1,0.6270,13.1670,2/21/2019,12:38,Cash,12.54,4.761905,0.6270,8.2
443,192-98-7397,C,Naypyitaw,Normal,Male,Fashion accessories,12.78,1,0.6390,13.4190,1/8/2019,14:11,Ewallet,12.78,4.761905,0.6390,9.5
402,236-86-3015,C,Naypyitaw,Member,Male,Home and lifestyle,13.98,1,0.6990,14.6790,2/4/2019,13:38,Ewallet,13.98,4.761905,0.6990,9.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4
699,751-41-9720,C,Naypyitaw,Normal,Male,Home and lifestyle,97.50,10,48.7500,1023.7500,1/12/2019,16:18,Ewallet,975.00,4.761905,48.7500,8.0
557,283-26-5248,C,Naypyitaw,Member,Female,Food and beverages,98.52,10,49.2600,1034.4600,1/30/2019,20:23,Ewallet,985.20,4.761905,49.2600,4.5
167,687-47-8271,A,Yangon,Normal,Male,Fashion accessories,98.98,10,49.4900,1039.2900,2/8/2019,16:20,Credit card,989.80,4.761905,49.4900,8.7
350,860-79-0874,C,Naypyitaw,Member,Female,Fashion accessories,99.30,10,49.6500,1042.6500,2/15/2019,14:53,Credit card,993.00,4.761905,49.6500,6.6

In [ ]:
# Visualizado apenas uma das colunas com os valores ordenados (ordem decrescente):
df['City'].sort_values(ascending = False)

0        Yangon
257      Yangon
534      Yangon
531      Yangon
530      Yangon
         ...
705    Mandalay
704    Mandalay
703    Mandalay
702    Mandalay
500    Mandalay
Name: City, Length: 1000, dtype: object

In [ ]:
# Aplicando o filtro por determinado tipo de dado existente em determinada coluna:
df[df['Product line'] == 'Electronic accessories']

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
5,699-14-3026,C,Naypyitaw,Normal,Male,Electronic accessories,85.39,7,29.8865,627.6165,3/25/2019,18:30,Ewallet,597.73,4.761905,29.8865,4.1
6,355-53-5943,A,Yangon,Member,Female,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,14:36,Ewallet,413.04,4.761905,20.6520,5.8
11,529-56-3974,B,Mandalay,Member,Male,Electronic accessories,25.51,4,5.1020,107.1420,3/9/2019,17:03,Cash,102.04,4.761905,5.1020,6.8
12,365-64-0515,A,Yangon,Normal,Female,Electronic accessories,46.95,5,11.7375,246.4875,2/12/2019,10:25,Ewallet,234.75,4.761905,11.7375,7.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
978,156-20-0370,B,Mandalay,Normal,Female,Electronic accessories,25.45,1,1.2725,26.7225,3/10/2019,18:10,Credit card,25.45,4.761905,1.2725,5.1
984,189-40-5216,C,Naypyitaw,Normal,Male,Electronic accessories,96.37,7,33.7295,708.3195,1/9/2019,11:40,Cash,674.59,4.761905,33.7295,6.0
988,267-62-7380,C,Naypyitaw,Member,Male,Electronic accessories,82.34,10,41.1700,864.5700,3/29/2019,19:12,Ewallet,823.40,4.761905,41.1700,4.3
992,745-74-0715,A,Yangon,Normal,Male,Electronic accessories,58.03,2,5.8030,121.8630,3/10/2019,20:46,Ewallet,116.06,4.761905,5.8030,8.8
994,652-49-6720,C,Naypyitaw,Member,Female,Electronic accessories,60.95,1,3.0475,63.9975,2/18/2019,11:40,Ewallet,60.95,4.761905,3.0475,5.9

In [ ]:
# Aplicando o filtro com mais de uma condição:
df_yangon_electronics = df[
  (df['City'] == 'Yangon') & (df['Product line'] == 'Electronic accessories')
]

df_yangon_electronics.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
6,355-53-5943,A,Yangon,Member,Female,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,14:36,Ewallet,413.04,4.761905,20.6520,5.8
12,365-64-0515,A,Yangon,Normal,Female,Electronic accessories,46.95,5,11.7375,246.4875,2/12/2019,10:25,Ewallet,234.75,4.761905,11.7375,7.1
23,636-48-8204,A,Yangon,Normal,Male,Electronic accessories,34.56,5,8.6400,181.4400,2/17/2019,11:15,Ewallet,172.80,4.761905,8.6400,9.9
37,272-65-1806,A,Yangon,Normal,Female,Electronic accessories,60.88,9,27.3960,575.3160,1/15/2019,17:17,Ewallet,547.92,4.761905,27.3960,4.7
95,594-34-4444,A,Yangon,Normal,Male,Electronic accessories,97.16,1,4.8580,102.0180,3/8/2019,20:38,Ewallet,97.16,4.761905,4.8580,7.2

In [ ]:
# Criando uma nova coluna e aplicando uma operação matemática entre as variáveis:
df['Ticket'] = df['Total'] / df['Quantity']
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,Ticket
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1,78.4245
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6,16.0440
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4,48.6465
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4,61.1310
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3,90.6255

### 4 - Utilizando funções agregadas:

In [ ]:
# Obtendo a média de valores de uma coluna:
df["Total"].mean()

NameError: ignored

In [ ]:
# Obtendo o valor mínimo de uma coluna:
df["Total"].min()

In [ ]:
# Obtendo o valor máximo de uma coluna:
df["Total"].max()

In [ ]:
# Retornando valores no quantil* fornecido sobre o eixo solicitado:
df.quantile(0.25)

In [ ]:
# Obtendo a moda de alguma coluna (valor que mais aparece):
df["Quantity"].mode()

In [ ]:
# Agregando mais de uma operação:
df['Rating'].agg([np.mean, max, min])

NameError: ignored

### 5 - Conhecendo outras operações, agrupamentos e slicing:

In [ ]:
# Deletando dados duplicados:
df_payments = df.drop_duplicates(subset = 'Payment')
df_payments

In [ ]:
# Recuperando a contagem de dados de acordo com as categorias:
df['Product line'].value_counts()

In [ ]:
# Utilizando o 'normalize' para retornar a frequência de valores únicos:
df[['Gender']].value_counts(normalize = True)

In [ ]:
# Realizando o agrupamento de 'Unit price' por 'Product line':
df.groupby("Product line")["Unit price"].mean().sort_values(ascending = False)

In [ ]:
# Agrupando com mais de uma variável:
df.groupby("Product line")[["Unit price", "Total"]].mean().sort_values("Total", ascending = False)

In [ ]:
# Agrupando com múltiplas estatísticas:
df.groupby("Product line")[["Quantity", "Total"]].agg([min, max,sum])

In [ ]:
# Mostrar as colunas existentes no Data Frame:
df.columns

In [ ]:
# Realizando o slicing com colunas:
df.loc[:, "City":"Product line"]

In [ ]:
# Realizando o slicing com posições:
df.iloc[2:10, 1:5]

In [ ]:
# Validando se existem valores ausentes (NaN = Not a Number):
df.isna().sum()

### 6 - Lidando com dados ausentes:

In [ ]:
# Criando uma lista por coluna
lista = {
  "nome": ["João", "Maria", "Caio", "Gabriela"],
  "sexo": ["H", "F", "M", "F"],
  "produto": ["abacate", "mamão", "laranja", "laranja"],
  "peso_kg": ["1.2", "2,5", "3.5", np.nan],
  "valor_total": [10.48, 22.5, 14.4, np.nan]
}

# Criando um novo dataframe
df2 = pd.DataFrame(lista)
df2

In [ ]:
# Total de valores ausentes por coluna
df2.isna().sum()

In [ ]:
# Plotando valores ausentes
df2.isna().sum().plot(kind="bar")

In [ ]:
# Removendo valores missing
df2.dropna()

In [ ]:
# Preenchendo valores ausentes, no caso abaixo com 0:
df2.fillna(0)